# Generated by Django 4.2.7 on 2025-10-29 05:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Very Good')])),
                ('energy_level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')])),
                ('anxiety_level', models.IntegerField(help_text='Rate from 1 (no anxiety) to 10 (severe anxiety)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MoodTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_positive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MoodEntryTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField(help_text='How much did this trigger affect you? (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mood_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='mood_tracker.moodentry')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood_tracker.moodtrigger')),
            ],
            options={
                'unique_together': {('mood_entry', 'trigger')},
            },
        ),
    ]
