# Generated by Django 4.2.7 on 2025-11-09 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('text_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('availability', models.CharField(default='24/7', max_length=100)),
                ('country', models.CharField(default='US', max_length=50)),
                ('is_crisis_line', models.BooleanField(default=True)),
                ('is_text_support', models.BooleanField(default=False)),
                ('is_chat_support', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Lower numbers = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-book', help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='blue', help_text='Color theme for category', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SelfCareActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('activity_type', models.CharField(choices=[('breathing', 'Breathing Exercise'), ('meditation', 'Meditation'), ('physical', 'Physical Activity'), ('creative', 'Creative Activity'), ('social', 'Social Activity'), ('mindfulness', 'Mindfulness'), ('journaling', 'Journaling'), ('relaxation', 'Relaxation')], max_length=20)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('benefits', models.TextField(blank=True, help_text='Benefits of this activity')),
                ('duration', models.CharField(choices=[('5', '5 minutes'), ('10', '10 minutes'), ('15', '15 minutes'), ('30', '30 minutes'), ('60', '1 hour')], default='10', max_length=10)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('tool', 'Interactive Tool'), ('worksheet', 'Worksheet'), ('guide', 'Guide'), ('external', 'External Link')], default='article', max_length=20)),
                ('summary', models.TextField(help_text='Brief description of the resource')),
                ('content', models.TextField(blank=True, help_text='Full content for articles/guides')),
                ('external_url', models.URLField(blank=True, help_text='External link for videos/tools')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_read_time', models.PositiveIntegerField(default=5, help_text='Estimated time in minutes')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.resourcecategory')),
            ],
            options={
                'ordering': ['-is_featured', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserResourceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
