# Generated by Django 4.2.7 on 2025-11-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelfCareActivity',
        ),
    ]
