# Generated by Django 4.2.7 on 2025-11-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_delete_selfcareactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResourceBookmark',
        ),
    ]
